### ISSUE TITLE
mrc2stack fails with "MRC file has an unusual start: -180 -180 -43326"

### ISSUE THREAD

**Issue by magsol** [coderforlife/py-seg-tools#1]
I see the `IOError` in line 174 of mrc.py, but it's not clear to me what the fix would be. Has the .mrc header protocol changed since this utility was created?

For context: I am attempting to convert [this .mrc stack of 416,312 images](http://www.ebi.ac.uk/pdbe/emdb/empiar/entry/10015) to individual .png files.

**Comment by coderforlife** [comment]
The MRC converter was originally designed for IMOD MRC files and added the silly requirement that the header values for nxstart, nystart, and nzstart (the offset of the subimage) were all zero since IMOD never used them. In a newer version of these programs (currently unavailable) that requirement has been removed. 

You can remove the requirement as well by simply removing line 174 which won't effect anything else.

**Comment by magsol** [comment]
Ahh, excellent point. Works perfectly now. Thanks!
